### ISSUE TITLE
book: The Exim SMTP mail server, by Philip Hazel, 1st April 2007 | Heavily outdated content

### ISSUE THREAD

**Issue by Ricky-Tigg** [Exim/exim-website#5]
Hello. On the official [site](https://www.exim.org/), the mention of the _The Exim SMTP mail server_ book, by Philip Hazel, published 1st April 2007, **ISBN:** 978095445297, sadly illustrates the promotion of a documentation containing an heavily outdated content. At the time of its publication it could have dealt at best with subjects covered in release [v. 4.66](https://lists.exim.org/lurker/message/20070109.095146.f64a0777.fr.html) of Exim, 9th Jan 2007! That's something new reader focusing on an up-to-date documentation cannot miss. Regards.

**Comment by HeikoSchlittermann** [comment]
closed with 6356a0e
