### ISSUE TITLE
Obsolete link

### ISSUE THREAD

**Issue by Ricky-Tigg** [Exim/exim-website#6]
Hello. [Here](https://www.exim.org/), again, among the indicators revealing a poorly active project, along with the mention of an heavily outdated source of documentation, whichi is illustrated by the book _The Exim SMTP mail server_, by Philip Hazel, 1st April **2007**,  the link for _Smail 3_ not only illustrates an insecure protocol (HTTP), but also once opened –at our own risks, leads to a page where no mention of _Smail 3_ is present neither _Smail 3_ is covered in the web site it is redirected to nor elsewhere on internet.

**Comment by HeikoSchlittermann** [comment]
The project is active, see https://git.exim.org/, but yes, the website and its links are a bit unmaintained currently. Thanks for bringing this to our attention again.

**Comment by HeikoSchlittermann** [comment]
This closes #5 too
